from django.urls import path

from apps.books.views import (
    AllConceptsView,
    BookBlockDetailView,
    BookBlocksView,
    BookSemanticMapView,
    BookConceptsView,
    BookSummaryView,
    ConceptCompareView,
    ConceptDetailView,
    ConceptMentionEditView,
    ConceptMapView,
    ConceptMentionResetView,
    ConceptSearchView,
    ConfirmRotationView,
    ExportBookView,
    ProtectBookView,
    ReanalyzeBookView,
    StatsView,
    UploadBooksView,
    UserBookDetailView,
    UserBooksView,
)

urlpatterns = [
    path("books/", UserBooksView.as_view(), name="books-list"),
    path("books/upload/", UploadBooksView.as_view(), name="books-upload"),
    path("books/upload/confirm-rotation/", ConfirmRotationView.as_view(), name="books-upload-confirm-rotation"),
    path("books/<int:book_id>/", UserBookDetailView.as_view(), name="books-detail"),
    path("books/<int:book_id>/protect/", ProtectBookView.as_view(), name="books-protect"),
    path("books/<int:book_id>/reanalyze/", ReanalyzeBookView.as_view(), name="books-reanalyze"),
    path("books/<int:book_id>/summary/", BookSummaryView.as_view(), name="books-summary"),
    path("books/<int:book_id>/semantic-map/", BookSemanticMapView.as_view(), name="books-semantic-map"),
    path("books/<int:book_id>/blocks/", BookBlocksView.as_view(), name="books-blocks"),
    path("books/<int:book_id>/blocks/<int:block_id>/", BookBlockDetailView.as_view(), name="books-block-detail"),
    path("books/<int:book_id>/concepts/", BookConceptsView.as_view(), name="books-concepts"),
    path("books/<int:book_id>/export/", ExportBookView.as_view(), name="books-export"),
    path("concepts/", AllConceptsView.as_view(), name="concepts-list"),
    path("concepts/search/", ConceptSearchView.as_view(), name="concepts-search"),
    path("concepts/map/", ConceptMapView.as_view(), name="concepts-map"),
    path("concepts/<int:concept_id>/", ConceptDetailView.as_view(), name="concepts-detail"),
    path("concepts/<int:concept_id>/compare/", ConceptCompareView.as_view(), name="concepts-compare"),
    path("concepts/mentions/<int:mention_id>/edit/", ConceptMentionEditView.as_view(), name="concept-mention-edit"),
    path("concepts/mentions/<int:mention_id>/reset/", ConceptMentionResetView.as_view(), name="concept-mention-reset"),
    path("stats/", StatsView.as_view(), name="stats"),
]
