# Generated by Django 6.0.5 on 2026-05-18 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('embedding_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='globalbookcache',
            name='analysis_version',
            field=models.CharField(default='concept_rag_v1', max_length=64),
        ),
        migrations.AddField(
            model_name='globalbookcache',
            name='full_summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_summary', models.TextField(blank=True)),
                ('detailed_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='books.globalbookcache')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('order_number', models.PositiveIntegerField()),
                ('source_text', models.TextField()),
                ('short_summary', models.TextField(blank=True)),
                ('start_paragraph', models.PositiveIntegerField(default=0)),
                ('end_paragraph', models.PositiveIntegerField(default=0)),
                ('chapter_title', models.CharField(blank=True, max_length=512)),
                ('embedding_id', models.CharField(blank=True, max_length=255, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_blocks', to='books.globalbookcache')),
            ],
            options={
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='ConceptMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_explanation', models.TextField()),
                ('source_quote', models.TextField(blank=True)),
                ('importance_score', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='books.concept')),
                ('global_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mentions', to='books.globalbookcache')),
                ('logical_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mentions', to='books.logicalblock')),
            ],
            options={
                'ordering': ('-importance_score', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserConceptEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_explanation', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edits', to='books.conceptmention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='logicalblock',
            index=models.Index(fields=['global_book', 'order_number'], name='books_logic_global__3d838c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='logicalblock',
            unique_together={('global_book', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='conceptmention',
            index=models.Index(fields=['global_book', 'concept'], name='books_conce_global__88ecb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptmention',
            unique_together={('concept', 'logical_block')},
        ),
        migrations.AlterUniqueTogether(
            name='userconceptedit',
            unique_together={('user', 'concept_mention')},
        ),
    ]
