# Generated by Django 6.0.5 on 2026-05-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_concept_globalbookcache_analysis_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('order_number', models.PositiveIntegerField()),
                ('start_block_number', models.PositiveIntegerField(default=1)),
                ('end_block_number', models.PositiveIntegerField(default=1)),
                ('start_paragraph', models.PositiveIntegerField(default=0)),
                ('end_paragraph', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('embedding_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='books.globalbookcache')),
            ],
            options={
                'ordering': ('order_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ThemeSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('source_quote', models.TextField(blank=True)),
                ('importance_score', models.FloatField(default=0.5)),
                ('start_paragraph', models.PositiveIntegerField(default=0)),
                ('end_paragraph', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='books.booktheme')),
            ],
            options={
                'ordering': ('-importance_score', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='booktheme',
            index=models.Index(fields=['global_book', 'order_number'], name='books_bookt_global__0f35bc_idx'),
        ),
        migrations.AddIndex(
            model_name='booktheme',
            index=models.Index(fields=['global_book', 'chapter_title'], name='books_bookt_global__a0d4b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booktheme',
            unique_together={('global_book', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='themesubtopic',
            index=models.Index(fields=['theme', 'importance_score'], name='books_theme_theme_i_d88b43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='themesubtopic',
            unique_together={('theme', 'normalized_name')},
        ),
    ]
