# Generated by Django 6.0.5 on 2026-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booktheme_themesubtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalblock',
            name='concept_candidates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logicalblock',
            name='semantic_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logicalblock',
            name='source_sentence_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logicalblock',
            name='thought_cluster_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
