# Generated by Django 6.0.5 on 2026-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_logicalblock_concept_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='analysis_mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userbook',
            name='current_stage',
            field=models.CharField(blank=True, default='uploaded', max_length=64),
        ),
        migrations.AddField(
            model_name='userbook',
            name='fallback_used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbook',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='llm_calls_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbook',
            name='llm_failures_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbook',
            name='llm_model_used',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userbook',
            name='llm_provider_used',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userbook',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbook',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('parsing', 'Parsing'), ('structure_detection', 'Structure Detection'), ('filtering', 'Filtering'), ('chunking', 'Chunking'), ('llm_section_analysis', 'LLM Section Analysis'), ('llm_chapter_analysis', 'LLM Chapter Analysis'), ('llm_book_analysis', 'LLM Book Analysis'), ('building_map', 'Building Map'), ('saving_results', 'Saving Results'), ('ready', 'Ready'), ('partial_ready', 'Partial Ready'), ('failed', 'Failed'), ('failed_timeout', 'Failed Timeout'), ('cancelled', 'Cancelled'), ('debug_preview', 'Debug Preview'), ('heuristic_preview', 'Heuristic Preview')], default='uploaded', max_length=20),
        ),
    ]
