# Generated by Django 6.0.5 on 2026-06-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_userbook_status_llmanalysisrun_llmbookanalysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('parsing', 'Parsing'), ('structure_detection', 'Structure Detection'), ('filtering', 'Filtering'), ('chunking', 'Chunking'), ('llm_section_analysis', 'LLM Section Analysis'), ('llm_chapter_analysis', 'LLM Chapter Analysis'), ('llm_book_analysis', 'LLM Book Analysis'), ('llm_fast_batched_section_analysis', 'LLM Fast Batched Section Analysis'), ('llm_fast_batched_chapter_analysis', 'LLM Fast Batched Chapter Analysis'), ('llm_fast_batched_book_analysis', 'LLM Fast Batched Book Analysis'), ('building_map', 'Building Map'), ('saving_results', 'Saving Results'), ('ready', 'Ready'), ('ready_with_warnings', 'Ready with Warnings'), ('partial_ready', 'Partial Ready'), ('failed', 'Failed'), ('failed_timeout', 'Failed Timeout'), ('cancelled', 'Cancelled'), ('debug_preview', 'Debug Preview'), ('heuristic_preview', 'Heuristic Preview')], default='uploaded', max_length=64),
        ),
    ]
