# Generated by Django 6.0.5 on 2026-06-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_userbook_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStudyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('content_markdown', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='books.userbook')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.llmanalysisrun')),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'status'], name='books_books_book_id_ba4b1b_idx')],
            },
        ),
    ]
