# Generated by Django 6.0.5 on 2026-06-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookstudynotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('source_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_end', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter_title', models.CharField(blank=True, max_length=512)),
                ('section_title', models.CharField(blank=True, max_length=512)),
                ('paragraph_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='books.userbook')),
                ('global_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='books.globalbookcache')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='GlobalLogicalThoughtBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('main_idea', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_books', models.ManyToManyField(blank=True, related_name='global_thought_blocks', to='books.userbook')),
            ],
            options={
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SentenceThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('thought_text', models.TextField()),
                ('normalized_thought', models.TextField(blank=True)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('is_meaningful', models.BooleanField(default=True)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('llm_raw_response', models.JSONField(blank=True, default=dict)),
                ('json_valid', models.BooleanField(default=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_thoughts', to='books.userbook')),
                ('global_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_thoughts', to='books.globalbookcache')),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thought', to='books.booksentence')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='SequentialThoughtGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('start_sentence_index', models.PositiveIntegerField()),
                ('end_sentence_index', models.PositiveIntegerField()),
                ('main_thought', models.TextField()),
                ('sentence_indexes', models.JSONField(default=list)),
                ('thought_ids', models.JSONField(default=list)),
                ('llm_raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequential_thought_groups', to='books.userbook')),
                ('global_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequential_thought_groups', to='books.globalbookcache')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ThoughtBlockMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('llm_raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='books.globallogicalthoughtblock')),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_memberships', to='books.sentencethought')),
            ],
        ),
        migrations.CreateModel(
            name='ThoughtChainAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('partial_ready', 'Partial Ready'), ('failed', 'Failed'), ('dry_run', 'Dry Run')], default='pending', max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('total_sentences', models.PositiveIntegerField(default=0)),
                ('processed_sentences', models.PositiveIntegerField(default=0)),
                ('total_thoughts', models.PositiveIntegerField(default=0)),
                ('total_relations_checked', models.PositiveIntegerField(default=0)),
                ('total_relations_created', models.PositiveIntegerField(default=0)),
                ('total_blocks_created', models.PositiveIntegerField(default=0)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_chain_runs', to='books.userbook')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ThoughtRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('same', 'Same'), ('related', 'Related'), ('different', 'Different')], max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True)),
                ('llm_raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='books.sentencethought')),
                ('target_thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='books.sentencethought')),
            ],
        ),
        migrations.AddIndex(
            model_name='booksentence',
            index=models.Index(fields=['book', 'index'], name='books_books_book_id_003656_idx'),
        ),
        migrations.AddIndex(
            model_name='booksentence',
            index=models.Index(fields=['global_book', 'chapter_title'], name='books_books_global__6e4591_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booksentence',
            unique_together={('global_book', 'index')},
        ),
        migrations.AddIndex(
            model_name='sentencethought',
            index=models.Index(fields=['book', 'is_meaningful'], name='books_sente_book_id_d4f45c_idx'),
        ),
        migrations.AddIndex(
            model_name='sentencethought',
            index=models.Index(fields=['global_book', 'index'], name='books_sente_global__88fa44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentencethought',
            unique_together={('global_book', 'index')},
        ),
        migrations.AddIndex(
            model_name='sequentialthoughtgroup',
            index=models.Index(fields=['book', 'index'], name='books_seque_book_id_25a922_idx'),
        ),
        migrations.AddIndex(
            model_name='sequentialthoughtgroup',
            index=models.Index(fields=['global_book', 'start_sentence_index'], name='books_seque_global__030fb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequentialthoughtgroup',
            unique_together={('global_book', 'index')},
        ),
        migrations.AddIndex(
            model_name='thoughtblockmembership',
            index=models.Index(fields=['block', 'relevance_score'], name='books_thoug_block_i_a866c1_idx'),
        ),
        migrations.AddIndex(
            model_name='thoughtblockmembership',
            index=models.Index(fields=['thought'], name='books_thoug_thought_7ea2b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thoughtblockmembership',
            unique_together={('thought', 'block')},
        ),
        migrations.AddIndex(
            model_name='thoughtchainanalysisrun',
            index=models.Index(fields=['book', 'status'], name='books_thoug_book_id_79f6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='thoughtchainanalysisrun',
            index=models.Index(fields=['created_at'], name='books_thoug_created_8cfe7f_idx'),
        ),
        migrations.AddIndex(
            model_name='thoughtrelation',
            index=models.Index(fields=['relation', 'score'], name='books_thoug_relatio_a8bf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='thoughtrelation',
            index=models.Index(fields=['source_thought', 'target_thought'], name='books_thoug_source__53f268_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thoughtrelation',
            unique_together={('source_thought', 'target_thought')},
        ),
    ]
